import { Metadata } from "next";
import Link from "next/link";

async function getData() {
  const response = await fetch("https://jsonplaceholder.typicode.com/posts", {
    next: {
      revalidate: 60,
    },
  });
  if (!response.ok) throw new Error("Unable to fetch posts!");
  return response.json();
}

export const metadata: Metadata = {
  title: "Blog | Next App",
  description: "Generated by create next app",
};

export default async function Blog() {
  const posts = await getData();
  return (
    <>
      <h1>Blog page</h1>
      <ul className="list-col">
        {posts.map((post: any) => (
          <Link href={`/blog/${post.id}`} key={post.id} className="button">
            {post.title}
          </Link>
        ))}
      </ul>
    </>
  );
}
